# Generated by Django 2.2.1 on 2019-06-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190621_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
