# Generated by Django 2.2.1 on 2019-07-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190701_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='icon',
        ),
    ]
