# Generated by Django 2.2.1 on 2019-07-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_tag_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parsed_markdown',
        ),
    ]
