# Generated by Django 2.2.1 on 2019-07-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190708_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
